# Generated by Django 5.2.6 on 2025-09-21 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('estacao', 'Estação de Trabalho'), ('sala', 'Sala de Reunião'), ('auditorio', 'Auditório')], max_length=20)),
                ('capacidade', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('data_reserva', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('periodo', models.CharField(max_length=20)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('cancelada', 'Cancelada')], default='ativo', max_length=10)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.ambiente')),
            ],
        ),
    ]
