# Generated by Django 5.2.6 on 2025-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estacao',
            field=models.CharField(default='Estação A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='periodo',
            field=models.CharField(default='Estação A', max_length=20),
            preserve_default=False,
        ),
    ]
