# Generated by Django 5.2.6 on 2025-09-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estacao',
            new_name='Ambiente',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='estacao',
            new_name='ambiente',
        ),
    ]
